import cron from "node-cron";
import { findDuplicateClusters } from "../src/cluster.js";
import { createEmbeddingProvider, prepareEmbeddingText } from "../src/embeddings.js";
import { GitHubClient } from "../src/github.js";
import type { IncidentWindow } from "../src/incident.js";
import { loadRepoConfig, type RepoClusterConfig } from "./config.js";
import { itemMetadata } from "../src/metadata.js";
import { escapeTableCell } from "../src/sanitize.js";
import type { Cluster, PRItem, StoreItem } from "../src/types.js";
import {
  drainWebhookQueue,
  getItemCountSince,
  getRepoStatus,
  listInstalledRepos,
  openRepoDB,
  setRepoScanning,
} from "./db.js";
import type { TriageConfig } from "./triage.js";
import { triageNewItem } from "./triage.js";
import type { WebhookEvent } from "./webhook.js";

export interface BacklogScanConfig {
  dataDir: string;
  jinaApiKey: string;
  githubToken: string;
  similarityThreshold: number;
  /** Repository-wide close events from this repo's config.json. When any are
   * declared the scan also fetches closed items, since a window can only match
   * against a `closedAt` the scan actually captured. */
  incidents?: IncidentWindow[];
  /** This repo's `cluster` block. Without it the App would honour only the
   * built-in bot list while the CLI honoured the repo's own additions. */
  cluster?: RepoClusterConfig;
}

/**
 * Whether a backlog scan fetches closed items in addition to open ones.
 *
 * Closed items cost API calls and only earn them when a window could match
 * one: an incident window tests `closedAt`, which is absent unless the scan
 * captured it. A repo with no incidents declared fetches open only.
 */
export function backlogFetchesClosed(incidents: readonly unknown[] | undefined): boolean {
  return Boolean(incidents && incidents.length > 0);
}

/**
 * The lower bound for a backlog scan's fetch.
 *
 * backlogFetchState only decides open-vs-all. Without a bound as well, a single
 * declared window flips the scan to every closed item the repository has ever
 * had, which for a large repo is most of its history. An item closed by an
 * incident was necessarily updated at or after that window opened, so the
 * earliest window start is a safe lower bound: GitHub filters on updated_at,
 * which for these items is the close itself or later.
 */
export function backlogFetchSince(
  incidents: readonly { start: string }[] | undefined,
): string | undefined {
  if (!incidents || incidents.length === 0) return undefined;
  return incidents.reduce((earliest, w) => (Date.parse(w.start) < Date.parse(earliest) ? w.start : earliest), incidents[0].start);
}

/**
 * Format cluster data into a GitHub issue body for the initial triage report.
 * Reuses the verbose report format: summary table + expanded clusters.
 */
function formatTriageReport(owner: string, repo: string, totalItems: number, clusters: Cluster[]): string {
  const fullName = `${owner}/${repo}`;
  const totalDupes = clusters.reduce((s, c) => s + c.items.length, 0);

  let body = `## summary\n\n`;
  body += `- **${totalItems}** issues and PRs scanned\n`;
  body += `- **${clusters.length}** duplicate clusters found\n`;
  body += `- **${totalDupes}** items involved in duplicates\n\n`;

  if (clusters.length === 0) {
    body += `no duplicate clusters detected at the current similarity threshold. as new issues and PRs come in, pr-prism will flag potential duplicates in real time.\n`;
    return body + `\n*generated by [pr-prism](https://github.com/StressTestor/pr-prism)*`;
  }

  body += `## duplicate clusters\n\n`;
  body += `| # | size | avg similarity | best pick | theme |\n`;
  body += `|---|------|---------------|-----------|-------|\n`;

  for (const c of clusters) {
    const theme = escapeTableCell(c.theme, 60);
    body += `| ${c.id} | ${c.items.length} | ${(c.avgSimilarity * 100).toFixed(1)}% | [#${c.bestPick.number}](https://github.com/${fullName}/issues/${c.bestPick.number}) | ${theme} |\n`;
  }

  // expanded cluster details (top 20)
  const showClusters = clusters.slice(0, 20);
  body += `\n## cluster details\n\n`;

  for (const c of showClusters) {
    body += `### cluster ${c.id}: ${escapeTableCell(c.theme, 80)}\n\n`;
    body += `avg similarity: ${(c.avgSimilarity * 100).toFixed(1)}% | best pick: #${c.bestPick.number}\n\n`;
    body += `| # | type | title | score |\n`;
    body += `|---|------|-------|-------|\n`;

    for (const item of c.items) {
      const link = `[#${item.number}](https://github.com/${fullName}/issues/${item.number})`;
      body += `| ${link} | ${item.type} | ${escapeTableCell(item.title, 60)} | ${item.score.toFixed(2)} |\n`;
    }

    body += `\n`;
  }

  if (clusters.length > 20) {
    body += `*... and ${clusters.length - 20} more clusters*\n\n`;
  }

  body += `---\n*generated by [pr-prism](https://github.com/StressTestor/pr-prism)*`;
  return body;
}

/**
 * Run a full backlog scan for a repo: fetch all open issues/PRs, embed them,
 * store in DB, run clustering, and post an initial triage report as a GitHub issue.
 */
export async function runBacklogScan(
  owner: string,
  repo: string,
  config: BacklogScanConfig,
  postIssue: (repo: string, title: string, body: string) => Promise<void>,
  callbacks?: {
    postComment?: (repo: string, number: number, body: string) => Promise<void>;
    closeIssue?: (repo: string, number: number) => Promise<void>;
    fetchFileContent?: (repo: string, path: string) => Promise<string | null>;
  },
): Promise<void> {
  const fullName = `${owner}/${repo}`;
  console.log(`[backlog] starting backlog scan for ${fullName}`);

  setRepoScanning(owner, repo, true);

  try {
    // 1. set up embedding provider
    const embedder = await createEmbeddingProvider({
      provider: "jina",
      apiKey: config.jinaApiKey,
      model: "jina-embeddings-v3",
    });

    const dims = embedder.dimensions;
    const incidents = config.incidents ?? [];
    const store = openRepoDB(config.dataDir, owner, repo, dims, "jina-embeddings-v3", incidents);

    try {
      // 2. fetch PRs + issues via REST (avoids 502s on large repos)
      const github = new GitHubClient(config.githubToken, owner, repo);

      // Closed items are only worth their API cost when a window could match
      // one. A repo with no incidents declared keeps fetching open items only.
      // Open and closed are fetched separately on purpose. `since` aborts a
      // fetch at the first item updated before it, and the lists are sorted by
      // updated desc, so a single state:"all" call bounded by `since` would
      // also drop open items nobody has touched lately - exactly the stale
      // duplicates a backlog scan exists to find. Open is therefore unbounded,
      // and only the closed pass carries the window bound.
      console.log(`[backlog] ${fullName}: fetching open PRs...`);
      const prs = await github.fetchPRs({ state: "open", maxItems: 5000, batchSize: 100 });
      console.log(`[backlog] ${fullName}: fetching open issues...`);
      const issues = await github.fetchIssues({ state: "open", maxItems: 5000, batchSize: 100 });

      if (backlogFetchesClosed(incidents)) {
        const since = backlogFetchSince(incidents);
        console.log(`[backlog] ${fullName}: fetching closed items updated since ${since}...`);
        prs.push(...(await github.fetchPRs({ state: "closed", since, maxItems: 5000, batchSize: 100 })));
        issues.push(...(await github.fetchIssues({ state: "closed", since, maxItems: 5000, batchSize: 100 })));
      }
      console.log(`[backlog] ${fullName}: fetched ${prs.length} PRs, ${issues.length} issues`);

      const allItems: PRItem[] = [...prs, ...issues];

      if (allItems.length === 0) {
        console.log(`[backlog] ${fullName}: no items found, skipping`);
        store.setMeta("last_sync", new Date().toISOString());
        return;
      }

      // 3. batch embed all items (batch size 50, with retry)
      console.log(`[backlog] ${fullName}: embedding ${allItems.length} items...`);
      const BATCH_SIZE = 50;
      let embedded = 0;

      for (let i = 0; i < allItems.length; i += BATCH_SIZE) {
        const batch = allItems.slice(i, i + BATCH_SIZE);
        const texts = batch.map((item) => prepareEmbeddingText(item));

        let embeddings: number[][];
        for (let attempt = 0; attempt < 3; attempt++) {
          try {
            embeddings = await embedder.embedBatch(texts);
            break;
          } catch (err: any) {
            const msg = err.message || "";
            if (attempt < 2) {
              const wait = msg.includes("429") ? 60 * (attempt + 1) : 5;
              console.warn(`[backlog] ${fullName}: embed batch failed (${msg.slice(0, 60)}), retrying in ${wait}s...`);
              await new Promise((r) => setTimeout(r, wait * 1000));
            } else {
              throw err;
            }
          }
        }

        // store each item
        for (let j = 0; j < batch.length; j++) {
          const item = batch[j];
          const embedding = new Float32Array(embeddings![j]);
          const storeItem: StoreItem = {
            id: `${fullName}:${item.type}:${item.number}`,
            type: item.type,
            number: item.number,
            repo: fullName,
            title: item.title,
            bodySnippet: (item.body || "").slice(0, 2000),
            embedding,
            // Single source for stored metadata. The hand-rolled literal that
            // was here had drifted from it, silently dropping bodyLength,
            // nodeId, headRefOid and closesIssues on every scheduled sync.
            metadata: itemMetadata(item),
            createdAt: item.createdAt,
            updatedAt: item.updatedAt,
          };
          store.upsert(storeItem);
        }

        embedded += batch.length;
        console.log(`[backlog] ${fullName}: embedded ${embedded}/${allItems.length}`);
      }

      // 4. run clustering
      console.log(`[backlog] ${fullName}: clustering...`);
      const items = store.getAllItems(fullName) as unknown as PRItem[];
      const clusters = findDuplicateClusters(store, items, {
        threshold: config.similarityThreshold,
        repo: fullName,
        includeBotAuthors: config.cluster?.includeBotAuthors,
        botAuthors: new Set(config.cluster?.botAuthors ?? []),
      });
      console.log(`[backlog] ${fullName}: found ${clusters.length} duplicate clusters`);

      // 5. post initial triage report
      const reportBody = formatTriageReport(owner, repo, allItems.length, clusters);
      const reportTitle = `pr-prism: initial triage report (${allItems.length} items scanned, ${clusters.length} duplicate clusters)`;

      await postIssue(fullName, reportTitle, reportBody);
      console.log(`[backlog] ${fullName}: posted triage report`);

      // 6. set last_sync
      store.setMeta("last_sync", new Date().toISOString());
    } finally {
      store.close();
    }
  } finally {
    // always clear scanning flag, even on error
    setRepoScanning(owner, repo, false);
  }

  // 7. drain webhook queue and process queued events
  const queued = drainWebhookQueue(owner, repo);
  if (queued.length > 0) {
    console.log(`[backlog] ${fullName}: processing ${queued.length} queued webhook events`);

    const triageConfig: TriageConfig = {
      dataDir: config.dataDir,
      jinaApiKey: config.jinaApiKey,
      similarityThreshold: config.similarityThreshold,
      autoClose: false,
      autoCloseThreshold: 0.95,
      // Drained events are triaged on the same terms as live ones. Omitting
      // this would filter bots on the webhook that arrived a second later and
      // not on the one that arrived during the scan.
      cluster: config.cluster,
    };

    const postComment =
      callbacks?.postComment ??
      (async (repo: string, number: number, body: string): Promise<void> => {
        console.log(`[triage] would post comment on ${repo}#${number}:\n${body}`);
      });
    const closeIssue =
      callbacks?.closeIssue ??
      (async (repo: string, number: number): Promise<void> => {
        console.log(`[triage] would close ${repo}#${number}`);
      });

    for (const event of queued) {
      try {
        await triageNewItem(event as WebhookEvent, triageConfig, postComment, closeIssue, callbacks?.fetchFileContent);
      } catch (err) {
        console.error(`[backlog] error processing queued event:`, err);
      }
    }
  }

  console.log(`[backlog] ${fullName}: backlog scan complete`);
}

// --- weekly digest ---

/** The digest reads per-repo settings itself, so it needs only the location of
 * the data directory. A global threshold here would be a lie: it applied to
 * every repo regardless of that repo's own configuration. */
export interface WeeklyDigestConfig {
  dataDir: string;
}

export interface RepoDigestData {
  owner: string;
  repo: string;
  totalItems: number;
  embeddingCount: number;
  newItemsThisWeek: number;
  clusterCount: number;
  biggestClusters: Cluster[];
  autoClosed: number;
}

/**
 * Get the ISO date string for last Monday at 00:00:00 UTC.
 * If today is Monday, returns today's midnight.
 */
export function getLastMonday(now?: Date): string {
  const d = now ? new Date(now) : new Date();
  const day = d.getUTCDay(); // 0=Sun, 1=Mon, ..., 6=Sat
  const diff = day === 0 ? 6 : day - 1; // days since last Monday
  d.setUTCDate(d.getUTCDate() - diff);
  d.setUTCHours(0, 0, 0, 0);
  return d.toISOString();
}

/**
 * Format a weekly digest issue body from repo digest data.
 */
export function formatWeeklyDigest(repos: RepoDigestData[], weekOf: string): string {
  const totalNew = repos.reduce((s, r) => s + r.newItemsThisWeek, 0);
  const totalItems = repos.reduce((s, r) => s + r.totalItems, 0);
  const totalClusters = repos.reduce((s, r) => s + r.clusterCount, 0);
  const totalAutoClosed = repos.reduce((s, r) => s + r.autoClosed, 0);

  // no activity across all repos
  if (totalNew === 0) {
    return `no new items this week. ${totalItems} items indexed, ${totalClusters} duplicate clusters.\n\n*generated by [pr-prism](https://github.com/StressTestor/pr-prism)*`;
  }

  let body = `## weekly summary\n\n`;
  body += `- **${totalNew}** new items this week\n`;
  body += `- **${totalItems}** total items indexed\n`;
  body += `- **${totalClusters}** duplicate clusters\n`;
  if (totalAutoClosed > 0) {
    body += `- **${totalAutoClosed}** items auto-closed\n`;
  }
  body += `\n`;

  for (const r of repos) {
    const fullName = `${r.owner}/${r.repo}`;
    body += `### ${fullName}\n\n`;
    body += `- new items: **${r.newItemsThisWeek}**\n`;
    body += `- total indexed: **${r.totalItems}** (${r.embeddingCount} embedded)\n`;
    body += `- duplicate clusters: **${r.clusterCount}**\n`;
    if (r.autoClosed > 0) {
      body += `- auto-closed: **${r.autoClosed}**\n`;
    }

    if (r.biggestClusters.length > 0) {
      body += `\n**biggest unresolved clusters:**\n\n`;
      body += `| # | size | avg similarity | theme |\n`;
      body += `|---|------|---------------|-------|\n`;
      for (const c of r.biggestClusters.slice(0, 5)) {
        const theme = escapeTableCell(c.theme, 60);
        body += `| ${c.id} | ${c.items.length} | ${(c.avgSimilarity * 100).toFixed(1)}% | ${theme} |\n`;
      }
    }

    body += `\n`;
  }

  body += `---\n*generated by [pr-prism](https://github.com/StressTestor/pr-prism)*`;
  return body;
}

/**
 * Start the weekly digest cron job. Runs every Monday at 9:00 AM UTC.
 * For each installed repo, gathers stats and posts a GitHub issue.
 */
export function startWeeklyDigest(
  config: WeeklyDigestConfig,
  postIssue: (repo: string, title: string, body: string) => Promise<void>,
): void {
  // Monday at 9:00 AM UTC: minute hour day-of-month month day-of-week
  cron.schedule(
    "0 9 * * 1",
    async () => {
      console.log("[digest] running weekly digest...");

      try {
        const repos = listInstalledRepos(config.dataDir);
        if (repos.length === 0) {
          console.log("[digest] no installed repos, skipping");
          return;
        }

        const lastMonday = getLastMonday();
        const digestData: RepoDigestData[] = [];

        for (const { owner, repo } of repos) {
          const fullName = `${owner}/${repo}`;
          try {
            const status = getRepoStatus(config.dataDir, owner, repo);
            const newItems = getItemCountSince(config.dataDir, owner, repo, lastMonday);

            // run clustering to get current cluster state. per-repo config is
            // loaded here rather than taken from the digest's global config:
            // otherwise the digest reports different clusters than the backlog
            // scan for the same repo, having applied neither its incident
            // windows nor its bot logins.
            const repoConfig = loadRepoConfig(config.dataDir, owner, repo);
            let clusters: Cluster[] = [];
            try {
              const store = openRepoDB(config.dataDir, owner, repo, undefined, undefined, repoConfig.incidents);
              try {
                const items = store.getAllItems(fullName) as unknown as PRItem[];
                if (items.length > 0) {
                  clusters = findDuplicateClusters(store, items, {
                    threshold: repoConfig.similarityThreshold,
                    repo: fullName,
                    includeBotAuthors: repoConfig.cluster.includeBotAuthors,
                    botAuthors: new Set(repoConfig.cluster.botAuthors),
                  });
                }
              } finally {
                store.close();
              }
            } catch (err) {
              console.warn(`[digest] ${fullName}: clustering failed:`, err);
            }

            // sort clusters by size descending for "biggest unresolved"
            const sorted = [...clusters].sort((a, b) => b.items.length - a.items.length);

            digestData.push({
              owner,
              repo,
              totalItems: status.itemCount,
              embeddingCount: status.embeddingCount,
              newItemsThisWeek: newItems,
              clusterCount: clusters.length,
              biggestClusters: sorted.slice(0, 5),
              autoClosed: 0, // TODO: track auto-close count when auto-close is enabled
            });
          } catch (err) {
            console.error(`[digest] error processing ${fullName}:`, err);
          }
        }

        if (digestData.length === 0) {
          console.log("[digest] no repo data collected, skipping");
          return;
        }

        const weekOf = getLastMonday();
        const weekLabel = weekOf.slice(0, 10); // YYYY-MM-DD
        const body = formatWeeklyDigest(digestData, weekOf);
        const title = `pr-prism weekly digest — week of ${weekLabel}`;

        // post to each repo that had activity, or to the first repo if no activity
        const activeRepos = digestData.filter((r) => r.newItemsThisWeek > 0);
        const targets = activeRepos.length > 0 ? activeRepos : [digestData[0]];

        for (const r of targets) {
          const fullName = `${r.owner}/${r.repo}`;
          try {
            await postIssue(fullName, title, body);
            console.log(`[digest] posted weekly digest to ${fullName}`);
          } catch (err) {
            console.error(`[digest] failed to post digest to ${fullName}:`, err);
          }
        }

        console.log("[digest] weekly digest complete");
      } catch (err) {
        console.error("[digest] weekly digest failed:", err);
      }
    },
    {
      timezone: "UTC",
    },
  );

  console.log("[digest] weekly digest cron scheduled (Monday 9:00 AM UTC)");
}
