import { createEmbeddingProvider, prepareEmbeddingText } from "../src/embeddings.js";
import { GitHubClient } from "../src/github.js";
import { findDuplicateClusters } from "../src/cluster.js";
import type { PRItem, StoreItem, Cluster } from "../src/types.js";
import { drainWebhookQueue, openRepoDB, setRepoScanning } from "./db.js";
import { triageNewItem } from "./triage.js";
import type { TriageConfig } from "./triage.js";
import type { WebhookEvent } from "./webhook.js";

export interface BacklogScanConfig {
  dataDir: string;
  jinaApiKey: string;
  githubToken: string;
  similarityThreshold: number;
}

/**
 * Format cluster data into a GitHub issue body for the initial triage report.
 * Reuses the verbose report format: summary table + expanded clusters.
 */
function formatTriageReport(
  owner: string,
  repo: string,
  totalItems: number,
  clusters: Cluster[],
): string {
  const fullName = `${owner}/${repo}`;
  const totalDupes = clusters.reduce((s, c) => s + c.items.length, 0);

  let body = `## summary\n\n`;
  body += `- **${totalItems}** open issues and PRs scanned\n`;
  body += `- **${clusters.length}** duplicate clusters found\n`;
  body += `- **${totalDupes}** items involved in duplicates\n\n`;

  if (clusters.length === 0) {
    body += `no duplicate clusters detected at the current similarity threshold. as new issues and PRs come in, pr-prism will flag potential duplicates in real time.\n`;
    return body + `\n*generated by [pr-prism](https://github.com/StressTestor/pr-prism)*`;
  }

  body += `## duplicate clusters\n\n`;
  body += `| # | size | avg similarity | best pick | theme |\n`;
  body += `|---|------|---------------|-----------|-------|\n`;

  for (const c of clusters) {
    const theme = c.theme.replace(/\|/g, "\\|").slice(0, 60);
    body += `| ${c.id} | ${c.items.length} | ${(c.avgSimilarity * 100).toFixed(1)}% | [#${c.bestPick.number}](https://github.com/${fullName}/issues/${c.bestPick.number}) | ${theme} |\n`;
  }

  // expanded cluster details (top 20)
  const showClusters = clusters.slice(0, 20);
  body += `\n## cluster details\n\n`;

  for (const c of showClusters) {
    body += `### cluster ${c.id}: ${c.theme.slice(0, 80)}\n\n`;
    body += `avg similarity: ${(c.avgSimilarity * 100).toFixed(1)}% | best pick: #${c.bestPick.number}\n\n`;
    body += `| # | type | title | score |\n`;
    body += `|---|------|-------|-------|\n`;

    for (const item of c.items) {
      const link = `[#${item.number}](https://github.com/${fullName}/issues/${item.number})`;
      body += `| ${link} | ${item.type} | ${item.title.replace(/\|/g, "\\|").slice(0, 60)} | ${item.score.toFixed(2)} |\n`;
    }

    body += `\n`;
  }

  if (clusters.length > 20) {
    body += `*... and ${clusters.length - 20} more clusters*\n\n`;
  }

  body += `---\n*generated by [pr-prism](https://github.com/StressTestor/pr-prism)*`;
  return body;
}

/**
 * Run a full backlog scan for a repo: fetch all open issues/PRs, embed them,
 * store in DB, run clustering, and post an initial triage report as a GitHub issue.
 */
export async function runBacklogScan(
  owner: string,
  repo: string,
  config: BacklogScanConfig,
  postIssue: (repo: string, title: string, body: string) => Promise<void>,
): Promise<void> {
  const fullName = `${owner}/${repo}`;
  console.log(`[backlog] starting backlog scan for ${fullName}`);

  setRepoScanning(owner, repo, true);

  try {
    // 1. set up embedding provider
    const embedder = await createEmbeddingProvider({
      provider: "jina",
      apiKey: config.jinaApiKey,
      model: "jina-embeddings-v3",
    });

    const dims = embedder.dimensions;
    const store = openRepoDB(config.dataDir, owner, repo, dims, "jina-embeddings-v3");

    try {
      // 2. fetch all open PRs + issues via REST (avoids 502s on large repos)
      const github = new GitHubClient(config.githubToken, owner, repo);

      console.log(`[backlog] ${fullName}: fetching open PRs...`);
      const prs = await github.fetchPRs({ state: "open", maxItems: 5000, batchSize: 100 });
      console.log(`[backlog] ${fullName}: fetched ${prs.length} open PRs`);

      console.log(`[backlog] ${fullName}: fetching open issues...`);
      const issues = await github.fetchIssues({ state: "open", maxItems: 5000, batchSize: 100 });
      console.log(`[backlog] ${fullName}: fetched ${issues.length} open issues`);

      const allItems: PRItem[] = [...prs, ...issues];

      if (allItems.length === 0) {
        console.log(`[backlog] ${fullName}: no open items found, skipping`);
        store.setMeta("last_sync", new Date().toISOString());
        return;
      }

      // 3. batch embed all items (batch size 50, with retry)
      console.log(`[backlog] ${fullName}: embedding ${allItems.length} items...`);
      const BATCH_SIZE = 50;
      let embedded = 0;

      for (let i = 0; i < allItems.length; i += BATCH_SIZE) {
        const batch = allItems.slice(i, i + BATCH_SIZE);
        const texts = batch.map((item) => prepareEmbeddingText(item));

        let embeddings: number[][];
        for (let attempt = 0; attempt < 3; attempt++) {
          try {
            embeddings = await embedder.embedBatch(texts);
            break;
          } catch (err: any) {
            const msg = err.message || "";
            if (attempt < 2) {
              const wait = msg.includes("429") ? 60 * (attempt + 1) : 5;
              console.warn(
                `[backlog] ${fullName}: embed batch failed (${msg.slice(0, 60)}), retrying in ${wait}s...`,
              );
              await new Promise((r) => setTimeout(r, wait * 1000));
            } else {
              throw err;
            }
          }
        }

        // store each item
        for (let j = 0; j < batch.length; j++) {
          const item = batch[j];
          const embedding = new Float32Array(embeddings![j]);
          const storeItem: StoreItem = {
            id: `${fullName}:${item.type}:${item.number}`,
            type: item.type,
            number: item.number,
            repo: fullName,
            title: item.title,
            bodySnippet: (item.body || "").slice(0, 2000),
            embedding,
            metadata: {
              author: item.author,
              state: item.state,
              labels: item.labels,
              additions: item.additions,
              deletions: item.deletions,
              changedFiles: item.changedFiles,
              ciStatus: item.ciStatus,
              reviewCount: item.reviewCount,
              hasTests: item.hasTests,
            },
            createdAt: item.createdAt,
            updatedAt: item.updatedAt,
          };
          store.upsert(storeItem);
        }

        embedded += batch.length;
        console.log(`[backlog] ${fullName}: embedded ${embedded}/${allItems.length}`);
      }

      // 4. run clustering
      console.log(`[backlog] ${fullName}: clustering...`);
      const items = store.getAllItems(fullName) as unknown as PRItem[];
      const clusters = findDuplicateClusters(store, items, {
        threshold: config.similarityThreshold,
        repo: fullName,
      });
      console.log(`[backlog] ${fullName}: found ${clusters.length} duplicate clusters`);

      // 5. post initial triage report
      const reportBody = formatTriageReport(owner, repo, allItems.length, clusters);
      const reportTitle = `pr-prism: initial triage report (${allItems.length} items scanned, ${clusters.length} duplicate clusters)`;

      await postIssue(fullName, reportTitle, reportBody);
      console.log(`[backlog] ${fullName}: posted triage report`);

      // 6. set last_sync
      store.setMeta("last_sync", new Date().toISOString());
    } finally {
      store.close();
    }
  } finally {
    // always clear scanning flag, even on error
    setRepoScanning(owner, repo, false);
  }

  // 7. drain webhook queue and process queued events
  const queued = drainWebhookQueue(owner, repo);
  if (queued.length > 0) {
    console.log(`[backlog] ${fullName}: processing ${queued.length} queued webhook events`);

    const triageConfig: TriageConfig = {
      dataDir: config.dataDir,
      jinaApiKey: config.jinaApiKey,
      similarityThreshold: config.similarityThreshold,
      autoClose: false,
      autoCloseThreshold: 0.95,
    };

    // placeholder callbacks — same as index.ts until Task 8 adds real GitHub App auth
    const postComment = async (repo: string, number: number, body: string): Promise<void> => {
      console.log(`[triage] would post comment on ${repo}#${number}:\n${body}`);
    };
    const closeIssue = async (repo: string, number: number): Promise<void> => {
      console.log(`[triage] would close ${repo}#${number}`);
    };

    for (const event of queued) {
      try {
        await triageNewItem(event as WebhookEvent, triageConfig, postComment, closeIssue);
      } catch (err) {
        console.error(`[backlog] error processing queued event:`, err);
      }
    }
  }

  console.log(`[backlog] ${fullName}: backlog scan complete`);
}
