import cron from "node-cron";
import { createEmbeddingProvider, prepareEmbeddingText } from "../src/embeddings.js";
import { GitHubClient } from "../src/github.js";
import { findDuplicateClusters } from "../src/cluster.js";
import type { PRItem, StoreItem, Cluster } from "../src/types.js";
import { drainWebhookQueue, getItemCountSince, getRepoStatus, listInstalledRepos, openRepoDB, setRepoScanning } from "./db.js";
import { triageNewItem } from "./triage.js";
import type { TriageConfig } from "./triage.js";
import type { WebhookEvent } from "./webhook.js";

export interface BacklogScanConfig {
  dataDir: string;
  jinaApiKey: string;
  githubToken: string;
  similarityThreshold: number;
}

/**
 * Format cluster data into a GitHub issue body for the initial triage report.
 * Reuses the verbose report format: summary table + expanded clusters.
 */
function formatTriageReport(
  owner: string,
  repo: string,
  totalItems: number,
  clusters: Cluster[],
): string {
  const fullName = `${owner}/${repo}`;
  const totalDupes = clusters.reduce((s, c) => s + c.items.length, 0);

  let body = `## summary\n\n`;
  body += `- **${totalItems}** open issues and PRs scanned\n`;
  body += `- **${clusters.length}** duplicate clusters found\n`;
  body += `- **${totalDupes}** items involved in duplicates\n\n`;

  if (clusters.length === 0) {
    body += `no duplicate clusters detected at the current similarity threshold. as new issues and PRs come in, pr-prism will flag potential duplicates in real time.\n`;
    return body + `\n*generated by [pr-prism](https://github.com/StressTestor/pr-prism)*`;
  }

  body += `## duplicate clusters\n\n`;
  body += `| # | size | avg similarity | best pick | theme |\n`;
  body += `|---|------|---------------|-----------|-------|\n`;

  for (const c of clusters) {
    const theme = c.theme.replace(/\|/g, "\\|").slice(0, 60);
    body += `| ${c.id} | ${c.items.length} | ${(c.avgSimilarity * 100).toFixed(1)}% | [#${c.bestPick.number}](https://github.com/${fullName}/issues/${c.bestPick.number}) | ${theme} |\n`;
  }

  // expanded cluster details (top 20)
  const showClusters = clusters.slice(0, 20);
  body += `\n## cluster details\n\n`;

  for (const c of showClusters) {
    body += `### cluster ${c.id}: ${c.theme.slice(0, 80)}\n\n`;
    body += `avg similarity: ${(c.avgSimilarity * 100).toFixed(1)}% | best pick: #${c.bestPick.number}\n\n`;
    body += `| # | type | title | score |\n`;
    body += `|---|------|-------|-------|\n`;

    for (const item of c.items) {
      const link = `[#${item.number}](https://github.com/${fullName}/issues/${item.number})`;
      body += `| ${link} | ${item.type} | ${item.title.replace(/\|/g, "\\|").slice(0, 60)} | ${item.score.toFixed(2)} |\n`;
    }

    body += `\n`;
  }

  if (clusters.length > 20) {
    body += `*... and ${clusters.length - 20} more clusters*\n\n`;
  }

  body += `---\n*generated by [pr-prism](https://github.com/StressTestor/pr-prism)*`;
  return body;
}

/**
 * Run a full backlog scan for a repo: fetch all open issues/PRs, embed them,
 * store in DB, run clustering, and post an initial triage report as a GitHub issue.
 */
export async function runBacklogScan(
  owner: string,
  repo: string,
  config: BacklogScanConfig,
  postIssue: (repo: string, title: string, body: string) => Promise<void>,
  callbacks?: {
    postComment?: (repo: string, number: number, body: string) => Promise<void>;
    closeIssue?: (repo: string, number: number) => Promise<void>;
    fetchFileContent?: (repo: string, path: string) => Promise<string | null>;
  },
): Promise<void> {
  const fullName = `${owner}/${repo}`;
  console.log(`[backlog] starting backlog scan for ${fullName}`);

  setRepoScanning(owner, repo, true);

  try {
    // 1. set up embedding provider
    const embedder = await createEmbeddingProvider({
      provider: "jina",
      apiKey: config.jinaApiKey,
      model: "jina-embeddings-v3",
    });

    const dims = embedder.dimensions;
    const store = openRepoDB(config.dataDir, owner, repo, dims, "jina-embeddings-v3");

    try {
      // 2. fetch all open PRs + issues via REST (avoids 502s on large repos)
      const github = new GitHubClient(config.githubToken, owner, repo);

      console.log(`[backlog] ${fullName}: fetching open PRs...`);
      const prs = await github.fetchPRs({ state: "open", maxItems: 5000, batchSize: 100 });
      console.log(`[backlog] ${fullName}: fetched ${prs.length} open PRs`);

      console.log(`[backlog] ${fullName}: fetching open issues...`);
      const issues = await github.fetchIssues({ state: "open", maxItems: 5000, batchSize: 100 });
      console.log(`[backlog] ${fullName}: fetched ${issues.length} open issues`);

      const allItems: PRItem[] = [...prs, ...issues];

      if (allItems.length === 0) {
        console.log(`[backlog] ${fullName}: no open items found, skipping`);
        store.setMeta("last_sync", new Date().toISOString());
        return;
      }

      // 3. batch embed all items (batch size 50, with retry)
      console.log(`[backlog] ${fullName}: embedding ${allItems.length} items...`);
      const BATCH_SIZE = 50;
      let embedded = 0;

      for (let i = 0; i < allItems.length; i += BATCH_SIZE) {
        const batch = allItems.slice(i, i + BATCH_SIZE);
        const texts = batch.map((item) => prepareEmbeddingText(item));

        let embeddings: number[][];
        for (let attempt = 0; attempt < 3; attempt++) {
          try {
            embeddings = await embedder.embedBatch(texts);
            break;
          } catch (err: any) {
            const msg = err.message || "";
            if (attempt < 2) {
              const wait = msg.includes("429") ? 60 * (attempt + 1) : 5;
              console.warn(
                `[backlog] ${fullName}: embed batch failed (${msg.slice(0, 60)}), retrying in ${wait}s...`,
              );
              await new Promise((r) => setTimeout(r, wait * 1000));
            } else {
              throw err;
            }
          }
        }

        // store each item
        for (let j = 0; j < batch.length; j++) {
          const item = batch[j];
          const embedding = new Float32Array(embeddings![j]);
          const storeItem: StoreItem = {
            id: `${fullName}:${item.type}:${item.number}`,
            type: item.type,
            number: item.number,
            repo: fullName,
            title: item.title,
            bodySnippet: (item.body || "").slice(0, 2000),
            embedding,
            metadata: {
              author: item.author,
              state: item.state,
              labels: item.labels,
              additions: item.additions,
              deletions: item.deletions,
              changedFiles: item.changedFiles,
              ciStatus: item.ciStatus,
              reviewCount: item.reviewCount,
              hasTests: item.hasTests,
            },
            createdAt: item.createdAt,
            updatedAt: item.updatedAt,
          };
          store.upsert(storeItem);
        }

        embedded += batch.length;
        console.log(`[backlog] ${fullName}: embedded ${embedded}/${allItems.length}`);
      }

      // 4. run clustering
      console.log(`[backlog] ${fullName}: clustering...`);
      const items = store.getAllItems(fullName) as unknown as PRItem[];
      const clusters = findDuplicateClusters(store, items, {
        threshold: config.similarityThreshold,
        repo: fullName,
      });
      console.log(`[backlog] ${fullName}: found ${clusters.length} duplicate clusters`);

      // 5. post initial triage report
      const reportBody = formatTriageReport(owner, repo, allItems.length, clusters);
      const reportTitle = `pr-prism: initial triage report (${allItems.length} items scanned, ${clusters.length} duplicate clusters)`;

      await postIssue(fullName, reportTitle, reportBody);
      console.log(`[backlog] ${fullName}: posted triage report`);

      // 6. set last_sync
      store.setMeta("last_sync", new Date().toISOString());
    } finally {
      store.close();
    }
  } finally {
    // always clear scanning flag, even on error
    setRepoScanning(owner, repo, false);
  }

  // 7. drain webhook queue and process queued events
  const queued = drainWebhookQueue(owner, repo);
  if (queued.length > 0) {
    console.log(`[backlog] ${fullName}: processing ${queued.length} queued webhook events`);

    const triageConfig: TriageConfig = {
      dataDir: config.dataDir,
      jinaApiKey: config.jinaApiKey,
      similarityThreshold: config.similarityThreshold,
      autoClose: false,
      autoCloseThreshold: 0.95,
    };

    const postComment = callbacks?.postComment ?? (async (repo: string, number: number, body: string): Promise<void> => {
      console.log(`[triage] would post comment on ${repo}#${number}:\n${body}`);
    });
    const closeIssue = callbacks?.closeIssue ?? (async (repo: string, number: number): Promise<void> => {
      console.log(`[triage] would close ${repo}#${number}`);
    });

    for (const event of queued) {
      try {
        await triageNewItem(event as WebhookEvent, triageConfig, postComment, closeIssue, callbacks?.fetchFileContent);
      } catch (err) {
        console.error(`[backlog] error processing queued event:`, err);
      }
    }
  }

  console.log(`[backlog] ${fullName}: backlog scan complete`);
}

// --- weekly digest ---

export interface WeeklyDigestConfig {
  dataDir: string;
  similarityThreshold: number;
  autoClose: boolean;
}

export interface RepoDigestData {
  owner: string;
  repo: string;
  totalItems: number;
  embeddingCount: number;
  newItemsThisWeek: number;
  clusterCount: number;
  biggestClusters: Cluster[];
  autoClosed: number;
}

/**
 * Get the ISO date string for last Monday at 00:00:00 UTC.
 * If today is Monday, returns today's midnight.
 */
export function getLastMonday(now?: Date): string {
  const d = now ? new Date(now) : new Date();
  const day = d.getUTCDay(); // 0=Sun, 1=Mon, ..., 6=Sat
  const diff = day === 0 ? 6 : day - 1; // days since last Monday
  d.setUTCDate(d.getUTCDate() - diff);
  d.setUTCHours(0, 0, 0, 0);
  return d.toISOString();
}

/**
 * Format a weekly digest issue body from repo digest data.
 */
export function formatWeeklyDigest(
  repos: RepoDigestData[],
  weekOf: string,
): string {
  const totalNew = repos.reduce((s, r) => s + r.newItemsThisWeek, 0);
  const totalItems = repos.reduce((s, r) => s + r.totalItems, 0);
  const totalClusters = repos.reduce((s, r) => s + r.clusterCount, 0);
  const totalAutoClosed = repos.reduce((s, r) => s + r.autoClosed, 0);

  // no activity across all repos
  if (totalNew === 0) {
    return `no new items this week. ${totalItems} items indexed, ${totalClusters} duplicate clusters.\n\n*generated by [pr-prism](https://github.com/StressTestor/pr-prism)*`;
  }

  let body = `## weekly summary\n\n`;
  body += `- **${totalNew}** new items this week\n`;
  body += `- **${totalItems}** total items indexed\n`;
  body += `- **${totalClusters}** duplicate clusters\n`;
  if (totalAutoClosed > 0) {
    body += `- **${totalAutoClosed}** items auto-closed\n`;
  }
  body += `\n`;

  for (const r of repos) {
    const fullName = `${r.owner}/${r.repo}`;
    body += `### ${fullName}\n\n`;
    body += `- new items: **${r.newItemsThisWeek}**\n`;
    body += `- total indexed: **${r.totalItems}** (${r.embeddingCount} embedded)\n`;
    body += `- duplicate clusters: **${r.clusterCount}**\n`;
    if (r.autoClosed > 0) {
      body += `- auto-closed: **${r.autoClosed}**\n`;
    }

    if (r.biggestClusters.length > 0) {
      body += `\n**biggest unresolved clusters:**\n\n`;
      body += `| # | size | avg similarity | theme |\n`;
      body += `|---|------|---------------|-------|\n`;
      for (const c of r.biggestClusters.slice(0, 5)) {
        const theme = c.theme.replace(/\|/g, "\\|").slice(0, 60);
        body += `| ${c.id} | ${c.items.length} | ${(c.avgSimilarity * 100).toFixed(1)}% | ${theme} |\n`;
      }
    }

    body += `\n`;
  }

  body += `---\n*generated by [pr-prism](https://github.com/StressTestor/pr-prism)*`;
  return body;
}

/**
 * Start the weekly digest cron job. Runs every Monday at 9:00 AM UTC.
 * For each installed repo, gathers stats and posts a GitHub issue.
 */
export function startWeeklyDigest(
  config: WeeklyDigestConfig,
  postIssue: (repo: string, title: string, body: string) => Promise<void>,
): void {
  // Monday at 9:00 AM UTC: minute hour day-of-month month day-of-week
  cron.schedule("0 9 * * 1", async () => {
    console.log("[digest] running weekly digest...");

    try {
      const repos = listInstalledRepos(config.dataDir);
      if (repos.length === 0) {
        console.log("[digest] no installed repos, skipping");
        return;
      }

      const lastMonday = getLastMonday();
      const digestData: RepoDigestData[] = [];

      for (const { owner, repo } of repos) {
        const fullName = `${owner}/${repo}`;
        try {
          const status = getRepoStatus(config.dataDir, owner, repo);
          const newItems = getItemCountSince(config.dataDir, owner, repo, lastMonday);

          // run clustering to get current cluster state
          let clusters: Cluster[] = [];
          try {
            const store = openRepoDB(config.dataDir, owner, repo);
            try {
              const items = store.getAllItems(fullName) as unknown as PRItem[];
              if (items.length > 0) {
                clusters = findDuplicateClusters(store, items, {
                  threshold: config.similarityThreshold,
                  repo: fullName,
                });
              }
            } finally {
              store.close();
            }
          } catch (err) {
            console.warn(`[digest] ${fullName}: clustering failed:`, err);
          }

          // sort clusters by size descending for "biggest unresolved"
          const sorted = [...clusters].sort((a, b) => b.items.length - a.items.length);

          digestData.push({
            owner,
            repo,
            totalItems: status.itemCount,
            embeddingCount: status.embeddingCount,
            newItemsThisWeek: newItems,
            clusterCount: clusters.length,
            biggestClusters: sorted.slice(0, 5),
            autoClosed: 0, // TODO: track auto-close count when auto-close is enabled
          });
        } catch (err) {
          console.error(`[digest] error processing ${fullName}:`, err);
        }
      }

      if (digestData.length === 0) {
        console.log("[digest] no repo data collected, skipping");
        return;
      }

      const weekOf = getLastMonday();
      const weekLabel = weekOf.slice(0, 10); // YYYY-MM-DD
      const body = formatWeeklyDigest(digestData, weekOf);
      const title = `pr-prism weekly digest — week of ${weekLabel}`;

      // post to each repo that had activity, or to the first repo if no activity
      const activeRepos = digestData.filter((r) => r.newItemsThisWeek > 0);
      const targets = activeRepos.length > 0 ? activeRepos : [digestData[0]];

      for (const r of targets) {
        const fullName = `${r.owner}/${r.repo}`;
        try {
          await postIssue(fullName, title, body);
          console.log(`[digest] posted weekly digest to ${fullName}`);
        } catch (err) {
          console.error(`[digest] failed to post digest to ${fullName}:`, err);
        }
      }

      console.log("[digest] weekly digest complete");
    } catch (err) {
      console.error("[digest] weekly digest failed:", err);
    }
  }, {
    timezone: "UTC",
  });

  console.log("[digest] weekly digest cron scheduled (Monday 9:00 AM UTC)");
}
